version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    container_name: docker-django-vue-backend
    command: ./docker/backend_setup.sh
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: docker-django-vue-frontend
    command: ./docker/frontend_setup.sh
    volumes:
      - .:/app
    depends_on:
      - django
