version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    container_name: docker-django-vue-backend
    command: ./docker/backend_setup.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - vue
  vue:
    build:
      context: .
      dockerfile: docker/FrontendDockerfile
    container_name: docker-django-vue-frontend
    command: ./docker/frontend_setup.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - "8080:8080"
