version: "3.3"

services:
  django:
    build:
      context: .
      dockerfile: docker/BackendDockerfile
    container_name: docker-django-vue-backend
    command: ./docker/backend_setup.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - vue
  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: docker-django-vue-frontend
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "/app/node_modules"
      - ".:/app"
    ports:
      - "8081:8081"
    expose:
      - 8081
