version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    working_directory: ~/vue-django
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - heroku/install
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: cd frontend && npm install
      - run:
          name: Build
          command: cd frontend && npm run build
      - run: ls
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - build
