version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
