version: 2.1
jobs:
  build:
    working_directory: ~/vue-django
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - run: ls
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: cd frontend && npm install
      - run:
          name: Build
          command: cd frontend && npm run build

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
